In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv('homeprices.csv')
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
model = linear_model.LinearRegression()
model.fit(df[['area']], df.price)

LinearRegression()

In [4]:
model.coef_

array([135.78767123])

In [5]:
model.intercept_

180616.43835616432

In [7]:
model.predict(np.array(5000).reshape(-1, 1))

C:\Users\datas\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [8]:
import pickle

In [9]:
with open('model_pickle', 'wb') as f:
    pickle.dump(model, f)

In [10]:
with open('model_pickle', 'rb') as f:
    mp = pickle.load(f)

In [22]:
mp.predict(np.array(6000).reshape(-1, 1))

C:\Users\datas\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([995342.46575342])

In [26]:
from joblib import dump, load

In [25]:
dump(model, 'model_joblib')

['model_joblib']

In [27]:
mj = load('model_joblib')

In [29]:
mj.predict(np.array(5000).reshape(-1, 1))

C:\Users\datas\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [30]:
mj.coef_

array([135.78767123])