In [1]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
import numpy as np

In [2]:
iris = load_iris()

In [3]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [4]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

### Random Forest

In [5]:
r_forest = cross_val_score(RandomForestClassifier(), iris.data, iris.target)
r_forest

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [6]:
np.average(r_forest)

0.9666666666666668

### SVC

In [7]:
svc_model = cross_val_score(SVC(), iris.data, iris.target)
svc_model

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [8]:
np.average(svc_model)

0.9666666666666666

### Logistic Regression

In [9]:
logistic_model = cross_val_score(LogisticRegression(), iris.data, iris.target)
logistic_model

C:\Users\datas\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [10]:
np.average(logistic_model)

0.9733333333333334

### Decision Tree

In [11]:
decision_tree = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)
decision_tree

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

In [12]:
np.average(decision_tree)

0.9666666666666668

### Best score so far is from SVM: 9733333333333334